# Generated by Django 4.0.6 on 2022-11-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeticionesUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('intentos', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
